site_name: Cesar Servin
theme:
  name: material
  icon:
    logo: material/dna
  features:
    - navigation.tabs
    - navigation.sections
    # - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
      primary: deep purple
      accent: indigo 
    - scheme: slate 
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode    
      primary: deep purple
      accent: indigo

plugins:
  - search
    # - mkdocstrings:  # To generate documentation from the code docstrings
    #   handlers:
    #     python:
    #       paths: [ src ]  # search packages in the src folder
    #       options:
    #         show_root_heading: true

extra:
  generator: false
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/cesarservin
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/cesarservin/

markdown_extensions:

  # Python Markdown
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: false

  # Python Markdown Extensions
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde


copyright: |
  &copy; 2024 <a href="https://github.com/cesarservin"  target="_blank" rel="noopener">Cesar Servin</a>

nav: # Setting up the navigation. Te below list will be tabs on left panel
  - 'Home': index.md
  # - Structure:
  #     - 'Project': page2.md  # A markdown file for documenting the package structure